name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
        php:
          - 8.0
          - 7.4
          - 7.3
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: composer install
      - run: sh test/ab/run_ab_tests.sh
      - run: vendor/bin/phpunit

  PHPUnit-macOS:
    name: PHPUnit (macOS)
    runs-on: macos-10.15
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - run: composer install
      - run: sh test/ab/run_ab_tests.sh
      - run: vendor/bin/phpunit
